final materias = [
  "Fundamentos de Programación",
  "Cálculo I",
  "Cálculo II",
  "Algebra Lineal",
  "Química",
  "Biología",
  "Fundamentos de Programación",
  "Cálculo I",
  "Cálculo II",
  "Algebra Lineal",
  "Química",
  "Biología",
  "Fundamentos de Programación",
  "Cálculo I",
  "Cálculo II",
  "Algebra Lineal",
  "Química",
  "Biología",
  "Fundamentos de Programación",
  "Cálculo I",
  "Cálculo II",
  "Algebra Lineal",
  "Química",
  "Biología",
  "Fundamentos de Programación",
  "Cálculo I",
  "Cálculo II",
  "Algebra Lineal",
  "Química",
  "Biología",
  "Fundamentos de Programación",
  "Cálculo I",
  "Cálculo II",
  "Algebra Lineal",
  "Química",
  "Biología",
];
